//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RLPAKTOOL_NameSpace.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RLPAKTOOL_NameSpace.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ｱ=あ
        ///ｲ=い
        ///ｳ=う
        ///ｴ=え
        ///ｵ=お
        ///ｶ=か
        ///ｷ=き
        ///ｸ=く
        ///ｹ=け
        ///ｺ=こ
        ///ｻ=さ
        ///ｼ=し
        ///ｽ=す
        ///ｾ=せ
        ///ｿ=そ
        ///ﾀ=た
        ///ﾁ=ち
        ///ﾂ=つ
        ///ﾃ=て
        ///ﾄ=と
        ///ﾅ=な
        ///ﾆ=に
        ///ﾇ=ぬ
        ///ﾈ=ね
        ///ﾉ=の
        ///ﾊ=は
        ///ﾋ=ひ
        ///ﾌ=ふ
        ///ﾍ=へ
        ///ﾎ=ほ
        ///ﾏ=ま
        ///ﾐ=み
        ///ﾑ=む
        ///ﾒ=め
        ///ﾓ=も
        ///ﾔ=や
        ///ﾕ=ゆ
        ///ﾖ=よ
        ///ﾗ=ら
        ///ﾘ=り
        ///ﾙ=る
        ///ﾚ=れ
        ///ﾛ=ろ
        ///ﾜ=わ
        ///ｦ=を
        ///ﾝ=ん
        ///ｧ=ぁ
        ///ｨ=ぃ
        ///ｩ=ぅ
        ///ｪ=ぇ
        ///ｫ=ぉ
        ///ｬ=ゃ
        ///ｭ=ゅ
        ///ｮ=ょ
        ///ｯ=っ.
        /// </summary>
        internal static string kanaconv {
            get {
                return ResourceManager.GetString("kanaconv", resourceCulture);
            }
        }
    }
}
